# This file is machine-generated - editing it directly is not advised

[[Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[CompilerSupportLibraries_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "067567a322fe466c5ec8d01413eee7127bd11699"
uuid = "e66e0078-7015-5450-92f7-15fbd957f2ae"
version = "0.3.1+0"

[[CpuId]]
deps = ["Markdown", "Test"]
git-tree-sha1 = "f0464e499ab9973b43c20f8216d088b61fda80c6"
uuid = "adafc99b-e345-5852-983c-f28acb93d879"
version = "0.2.2"

[[Dates]]
deps = ["Printf"]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[Distributed]]
deps = ["Random", "Serialization", "Sockets"]
uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[[InteractiveUtils]]
deps = ["Markdown"]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[LibGit2]]
deps = ["Printf"]
uuid = "76f85450-5226-5b5a-8eaa-529ad045b433"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[LinearAlgebra]]
deps = ["Libdl"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"

[[LoopVectorization]]
deps = ["LinearAlgebra", "OffsetArrays", "SIMDPirates", "SLEEFPirates", "UnPack", "VectorizationBase"]
git-tree-sha1 = "b834b45299ff8508a4bf9b58d31b4a2d27268cd2"
repo-rev = "master"
repo-url = "https://github.com/chriselrod/LoopVectorization.jl"
uuid = "bdcacae8-1622-11e9-2a5c-532679323890"
version = "0.6.22"

[[Markdown]]
deps = ["Base64"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[OffsetArrays]]
git-tree-sha1 = "6a35d9446b40ae5004cd7bd0f1ae3505528c7fd6"
uuid = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
version = "1.0.3"

[[OpenSpecFun_jll]]
deps = ["CompilerSupportLibraries_jll", "Libdl", "Pkg"]
git-tree-sha1 = "d51c416559217d974a1113522d5919235ae67a87"
uuid = "efe28fd5-8261-553b-a9e1-b2916fc3738e"
version = "0.5.3+3"

[[OrderedCollections]]
deps = ["Random", "Serialization", "Test"]
git-tree-sha1 = "c4c13474d23c60d20a67b217f1d7f22a40edf8f1"
uuid = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
version = "1.1.0"

[[Parameters]]
deps = ["OrderedCollections"]
git-tree-sha1 = "b62b2558efb1eef1fa44e4be5ff58a515c287e38"
uuid = "d96e819e-fc66-5662-9728-84c9c7592b0a"
version = "0.12.0"

[[Pkg]]
deps = ["Dates", "LibGit2", "Libdl", "Logging", "Markdown", "Printf", "REPL", "Random", "SHA", "UUIDs"]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[[Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[REPL]]
deps = ["InteractiveUtils", "Markdown", "Sockets"]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[[Random]]
deps = ["Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[ReverseDiffExpressionsBase]]
deps = ["LinearAlgebra", "LoopVectorization", "OffsetArrays"]
git-tree-sha1 = "62a723d09a996587155e299043ff2a9325413b40"
repo-rev = "master"
repo-url = "https://github.com/chriselrod/ReverseDiffExpressionsBase.jl"
uuid = "6c4e8705-acc8-45e6-99c7-2e34d4f10b96"
version = "0.1.0"

[[SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[[SIMDPirates]]
deps = ["VectorizationBase"]
git-tree-sha1 = "1a9cbe1be1f5d43ac49eeb38ca64dd78e50a0cc6"
repo-rev = "master"
repo-url = "https://github.com/chriselrod/SIMDPirates.jl"
uuid = "21efa798-c60a-11e8-04d3-e1a92915a26a"
version = "0.7.3"

[[SLEEFPirates]]
deps = ["Libdl", "SIMDPirates", "VectorizationBase"]
git-tree-sha1 = "fd6c86c21bed132906aa457c7d2ae4e5ac1803e3"
repo-rev = "master"
repo-url = "https://github.com/chriselrod/SLEEFPirates.jl"
uuid = "476501e8-09a2-5ece-8869-fb82de89a1fa"
version = "0.4.3"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"

[[SpecialFunctions]]
deps = ["OpenSpecFun_jll"]
git-tree-sha1 = "e19b98acb182567bcb7b75bb5d9eedf3a3b5ec6c"
uuid = "276daf66-3868-5448-9aa4-cd146d93841b"
version = "0.10.0"

[[StackPointers]]
deps = ["VectorizationBase"]
git-tree-sha1 = "abf1f0d6b8e4eb2bba137d876e0cd9efa7bbf327"
repo-rev = "master"
repo-url = "https://github.com/chriselrod/StackPointers.jl"
uuid = "062a3e2c-34b1-4659-9cae-7af421e0d832"
version = "0.1.1"

[[Test]]
deps = ["Distributed", "InteractiveUtils", "Logging", "Random"]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[[UUIDs]]
deps = ["Random", "SHA"]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[[UnPack]]
git-tree-sha1 = "e0cb9715adda456f7657e45377fd3063bf87179a"
uuid = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"
version = "0.1.0"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[[VectorizationBase]]
deps = ["CpuId", "LinearAlgebra"]
git-tree-sha1 = "83e32d4835fc4f4ecfd43eb59fa7fc00854b3d41"
repo-rev = "master"
repo-url = "https://github.com/chriselrod/VectorizationBase.jl"
uuid = "3d5dd08c-fd9d-11e8-17fa-ed2836048c2f"
version = "0.9.4"

[[VectorizedRNG]]
deps = ["Distributed", "Random", "SIMDPirates", "VectorizationBase"]
git-tree-sha1 = "1334ca6ebdb7bc30308e504dd4786b7a06471060"
repo-rev = "master"
repo-url = "https://github.com/chriselrod/VectorizedRNG.jl"
uuid = "33b4df10-0173-11e9-2a0c-851a7edac40e"
version = "0.1.5"
